### ISSUE TITLE
사용자 접근 사이트 관련 로깅

### ISSUE THREAD

**Issue by Sim-mi-gyeong** [Sim-mi-gyeong/Prompter-BE#3]
## 💡 Issue
- [ ] 사용자 행동 패턴 관련 로깅을 통한 추천 기능 요구

## 📝  todo
- [ ] 사용자가 액세스하는 사이트에 대한 정보 로깅
- [ ] 사용자 행동 패턴 관련 추가 로깅
