### ISSUE TITLE
GPT 3.5/4 버전 분기 처리

### ISSUE THREAD

**Issue by Sim-mi-gyeong** [Sim-mi-gyeong/Prompter-BE#9]
## 💡 Issue
- [x] GPT 모델 사용 시 GPT 3.5/4 버전 분기 처리 필요

## 📝  todo
- [x] Front API 호출 시 GPT 사용 버전에 대한 Parameter 추가 필요
- [x] Parameter 에 따른 Core API 호출 분기 처리
